model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 20

exp_params:
  dataset: fashionmnist
  data_path: "../../shared/Data/"
  img_size: 28
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  #no_zsamp: 5

trainer_params:
  gpus: 0
  max_nb_epochs: 10
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
